### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by dadou181295** [edgar-zigis/MaterialTextField#11]
Hey, Any idea from where is that fatal crash ? 

`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference
com.zigis.materialtextfield.MaterialTextField.onTouchEvent
keyboard_arrow_down
`

`com.zigis.materialtextfield.MaterialTextField.onTouchEvent (MaterialTextField.java:93)
`

**Comment by edgar-zigis** [comment]
Do you use a recent version? Because this was fixed in this commit:
https://github.com/edgar-zigis/MaterialTextField/commit/ead4d24211bb442e730f7a343aee2fedc085f9b7
