### ISSUE TITLE
Bug editText password

### ISSUE THREAD

**Issue by dadou181295** [edgar-zigis/MaterialTextField#12]
When trying to print a password
`            val password = passWordEditText?.text.toString()
`
 input  I get
`  password: com.zigis.materialtextfield.MaterialTextField{910d1d7 VFED..CL. .F...... 44,1087-1036,1240 #7f0901d2  `

**Comment by edgar-zigis** [comment]
You clearly print object, not the text value. For me `passwordField.text.toString()` prints a correct password. Sometimes such things occur when you don't clean the project properly.
