### ISSUE TITLE
Android  11 crash 

### ISSUE THREAD

**Issue by Dave181295** [edgar-zigis/MaterialTextField#14]
Hello, thanks for your library. I got crash on Android 11 related to the XML
`Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.olivier.oplivre/com.olivier.oplivre.authentifications.RestaurantActivityLogin}: android.view.InflateException: Binary XML file line #33 in com.olivier.oplivre:layout/activity_restaurant_login: Binary XML file line #33 in com.olivier.oplivre:layout/activity_restaurant_login: Error inflating class com.zigis.materialtextfield.MaterialTextField`

`Caused by android.view.InflateException
Binary XML file line #33 in com.olivier.oplivre:layout/activity_restaurant_login: Binary XML file line #33 in com.olivier.oplivre:layout/activity_restaurant_login: Error inflating class com.zigis.materialtextfield.MaterialTextField`

**Comment by edgar-zigis** [comment]
Hey, sorry for late reply. This is quite uninformative crash. Some xml properties were renamed, please check whether all properties are named correctly. I got Android 11 myself and everything seems to work fine.

**Comment by edgar-zigis** [comment]
This library is used on the project with half a million users and no exceptions were identified. Please check whether you use library correctly.
