### ISSUE TITLE
Right icon occupies space even if it is not set, Also input type textMultiLine not supportrd

### ISSUE THREAD

**Issue by akankshapaul048** [edgar-zigis/MaterialTextField#3]
My input field contains large text, but the right icon space make it worst. 
Even the text is shown in single line after setting textMultiLine also. 

Please resolve the issue.
![Screenshot_2013-10-17-14-42-24](https://user-images.githubusercontent.com/35328127/64232835-5a203f80-cf10-11e9-8a3e-8672feb600cd.jpg)

**Comment by edgar-zigis** [comment]
Thank you for the reported issue. I will fix the issue regarding right icon and add multiline support.

**Comment by edgar-zigis** [comment]
I have fixed the issue regarding that odd space, you can pull the 1.1.2 library version to use this fix.
Multiline support, however, won't be supported, because it will bring some issues regarding hint etc.
I will consider adding multiline in case of it will be requested by more users.

**Comment by edgar-zigis** [comment]
@akankshapaul048 multiline support has been added by setting the external param `isMultiline` true
